const impactRank = { High: 3, Medium: 2, Low: 1 };
export class OpportunityEngine {
  generate({ pages, technical, keywords = [], business = {} }) { const opportunities = []; const add = (issue, reason, impact, priority, suggestedAction, url = null) => opportunities.push({ issue, reason, impact, priority, suggestedAction, url });
    for (const page of pages) { if (page.wordCount < 700) add("Content depth gap", `${page.url} has only ${page.wordCount} words`, "High", "High", `Expand the page to answer buyer questions, comparisons, process and FAQs; target at least ${page.wordCount < 300 ? 1200 : 1000} useful words.`, page.url); if (!page.schemaAnalysis?.types?.includes("FAQPage") && page.wordCount > 500) add("FAQ schema opportunity", "A substantial page can answer related questions in search results", "Medium", "Medium", "Add 3–6 genuine FAQs and valid FAQPage schema.", page.url); if ((page.internalLinkCount || 0) < 2) add("Internal link opportunity", "The page has weak internal discovery signals", "High", "High", "Add contextual links from relevant high-authority pages with descriptive anchors.", page.url); if ((page.content?.ctrScore || 0) < 70) add("Improve title CTR", "Title/meta length and messaging are unlikely to maximize clicks", "Medium", "Medium", "Rewrite around outcome, specificity and intent while staying within SERP limits.", page.url); }
    for (const keyword of keywords.filter((item) => item.priority === "High" || item.priority >= 70)) if (!pages.some((page) => `${page.title} ${page.url}`.toLowerCase().includes(String(keyword.keyword).toLowerCase()))) add("Missing keyword landing page", `No clear page targets ${keyword.keyword}`, "High", "Critical", `Create a ${keyword.searchIntent === "local" ? "location/service" : "focused"} page for “${keyword.keyword}”.`);
    if (business.city && !pages.some((page) => page.url.toLowerCase().includes(String(business.city).toLowerCase().replace(/\s+/g, "-")))) add("Location page opportunity", `No URL clearly targets ${business.city}`, "High", "High", `Create a useful ${business.city} location page with services, proof, FAQs and LocalBusiness schema.`);
    for (const issue of technical.issues.filter((item) => ["Critical", "High"].includes(item.severity)).slice(0, 20)) add(issue.type, issue.message, issue.severity, issue.severity, `Resolve ${issue.type.replaceAll("_", " ")} and validate with a fresh crawl.`, issue.url);
    return opportunities.sort((a, b) => (impactRank[b.impact] || 4) - (impactRank[a.impact] || 4)); }
}
