import { BaseAgent } from "../BaseAgent.js"; import { sendTransactionalEmail } from "../../services/email-service.js"; import { estimateMetrics } from "../agent-utils.js";
export class OutreachAgent extends BaseAgent {
  constructor(deps) { super({ id: "authority-outreach", name: "Authority Outreach Agent", description: "Creates personalized email, LinkedIn and follow-up sequences; sends only with one-time approval", ...deps }); }
  async execute(input, context) {
    const project = await context.db.collection("backlinkProjects").findOne({ _id: input.projectId, organizationId: context.organizationId }); if (!project) throw new Error("Backlink project not found");
    let canSend = false; if (input.sendApprovalId) { const approval = await context.db.collection("outreachSendApprovals").findOneAndUpdate({ _id: input.sendApprovalId, organizationId: context.organizationId, projectId: project._id, purpose: "outreach_send", status: "approved", expiresAt: { $gt: new Date() } }, { $set: { status: "consumed", consumedAt: new Date(), updatedAt: new Date() } }, { returnDocument: "after" }); canSend = Boolean(approval?.value || approval); }
    if (canSend && (input.prospects || []).length !== 1) throw new Error("Approved outreach sends require exactly one recipient");
    const prospects = (input.prospects || []).slice(0, 100).map((prospect) => personalize(project, prospect)), now = new Date(), emails = [];
    for (const prospect of prospects) { let delivery = { delivered: false, reason: "approval_required" }; if (canSend && prospect.email) delivery = await sendTransactionalEmail({ to: prospect.email, subject: prospect.emailSubject, text: prospect.emailBody }); emails.push({ prospect: prospect.domain, to: prospect.email || "", subject: prospect.emailSubject, body: prospect.emailBody, status: delivery.delivered ? "sent" : "draft", delivery }); }
    const campaign = { organizationId: context.organizationId, clientId: project.clientId, projectId: project._id, createdBy: context.userId, campaignName: input.campaignName || `${project.industry || "Authority"} outreach ${now.toISOString().slice(0, 10)}`, prospects, emails, status: emails.some((item) => item.status === "sent") ? "active" : "draft", responses: [], sendApproved: canSend, createdAt: now, updatedAt: now }, result = await context.db.collection("outreachCampaigns").insertOne(campaign); return { output: { ...campaign, _id: result.insertedId }, metrics: estimateMetrics(campaign) };
  }
}
function personalize(project, prospect) { const domain = prospect.domain || host(prospect.url), author = prospect.author || "editorial team", history = prospect.previousInteraction ? ` I appreciated our previous conversation about ${prospect.previousInteraction}.` : "", angle = prospect.angle || `a practical ${project.industry || "industry"} resource`; return { ...prospect, domain, emailSubject: prospect.subject || `Useful ${project.industry || "industry"} resource for ${domain}`, emailBody: `Hi ${author},\n\nI reviewed ${domain} and noticed your work on ${prospect.topic || project.industry || "the industry"}.${history} We have ${angle} that may genuinely help your readers: ${project.targetWebsite}.\n\nIf it fits your editorial standards, I would be glad to share more context or contribute an original expert section. No problem if it is not a fit.\n\nThanks,\n${project.brandName || "The team"}`, linkedinMessage: `Hi ${author}, I enjoyed your work on ${prospect.topic || project.industry}. We have a relevant evidence-led resource and I would value your editorial feedback.`, followUps: [{ afterDays: 4, message: "Just following up once in case the resource is useful for your readers. Happy to send a concise summary." }, { afterDays: 9, message: "Closing the loop—no need to reply if this is not relevant. Thank you for considering it." }] }; }
function host(value) { try { return new URL(value).hostname.replace(/^www\./, ""); } catch { return "prospect"; } }
