import { BaseAgent } from "../BaseAgent.js"; import { estimateMetrics } from "../agent-utils.js";
export class ReviewAgent extends BaseAgent {
  constructor(deps) { super({ id: "review", name: "Review Agent", description: "Creates personalized review requests, reminders, sentiment insights and owner replies", ...deps }); }
  async execute(input, context) {
    const customer = String(input.customerName || "Customer"), business = input.businessName || "our business", link = input.reviewLink || "[review link]", request = `Hi ${customer}, thank you for choosing ${business}. If you were happy with the experience, please share an honest Google review: ${link}`, reminder = `Hi ${customer}, a quick reminder—your feedback would really help ${business}. Thank you!`, email = { subject: `How was your experience with ${business}?`, body: `${request}\n\nThank you,\n${business}` }, whatsappUrl = input.phone ? `https://wa.me/${String(input.phone).replace(/\D/g, "")}?text=${encodeURIComponent(request)}` : null, rating = Number(input.rating || 0), reviewText = String(input.reviewText || ""), sentiment = analyze(reviewText, rating), ownerReply = buildReply({ customer, business, rating, sentiment, reviewText }), output = { request, reminder, email, whatsappUrl, suggestedReminderAt: input.reminderAt || new Date(Date.now() + 3 * 86400000), ownerReply, sentiment, status: rating ? "response_received" : "request_ready" };
    if (input.save) { const now = new Date(), record = { organizationId: context.organizationId, clientId: context.clientId, projectId: input.projectId || null, createdBy: context.userId, customerName: customer, email: input.email || "", phone: input.phone || "", rating, reviewText, source: input.source || "manual", responseStatus: rating ? "pending" : "requested", aiReply: ownerReply, sentiment, requestMessage: request, emailRequest: email, whatsappUrl, reminderAt: output.suggestedReminderAt, createdAt: now, updatedAt: now }; await context.db.collection("reviewRecords").insertOne(record); await context.db.collection("reviews").insertOne({ ...record, status: output.status, ownerReply }); }
    if (rating) await this.events.emit("review_received", { rating, customerName: customer, sentiment: sentiment.label }, context); return { output, metrics: estimateMetrics(output) };
  }
}
function analyze(text, rating) { const lower = text.toLowerCase(), praise = ["great", "excellent", "helpful", "professional", "fast", "quality", "recommend"].filter((word) => lower.includes(word)), complaints = ["late", "slow", "poor", "bad", "expensive", "rude", "issue", "problem"].filter((word) => lower.includes(word)), label = rating ? rating >= 4 ? "positive" : rating <= 2 ? "negative" : "neutral" : praise.length > complaints.length ? "positive" : complaints.length > praise.length ? "negative" : "neutral"; return { label, commonPraise: praise, commonComplaints: complaints }; }
function buildReply({ customer, business, rating, sentiment }) { if (sentiment.label === "positive" || rating >= 4) return `Thank you, ${customer}. We appreciate your feedback and are glad you had a positive experience with ${business}.`; if (sentiment.label === "negative" || (rating && rating <= 2)) return `Thank you for sharing this, ${customer}. We are sorry the experience fell short. Please contact ${business} directly so we can understand the details and work toward a resolution.`; return `Thank you for your feedback, ${customer}. We appreciate you taking the time to share your experience with ${business}.`; }
