import { AgentRegistry } from "./AgentRegistry.js";
import { SeoAuditAgent } from "./specialized/SeoAuditAgent.js"; import { TechnicalSeoAgent } from "./specialized/TechnicalSeoAgent.js"; import { ContentStrategyAgent } from "./specialized/ContentStrategyAgent.js"; import { BlogWriterAgent } from "./specialized/BlogWriterAgent.js"; import { WordPressAgent } from "./specialized/WordPressAgent.js"; import { GbpAgent } from "./specialized/GbpAgent.js"; import { ReviewAgent } from "./specialized/ReviewAgent.js"; import { BacklinkAgent } from "./specialized/BacklinkAgent.js"; import { InternalLinkingAgent } from "./specialized/InternalLinkingAgent.js"; import { SchemaAgent } from "./specialized/SchemaAgent.js"; import { ReportAgent } from "./specialized/ReportAgent.js"; import { NotificationAgent } from "./specialized/NotificationAgent.js";
import { SeoIntelligenceAgent } from "./specialized/SeoIntelligenceAgent.js"; import { SeoStrategistAgent } from "./specialized/SeoStrategistAgent.js"; import { AIQueryGeneratorAgent } from "./specialized/AIQueryGeneratorAgent.js"; import { AIVisibilityMonitorAgent } from "./specialized/AIVisibilityMonitorAgent.js"; import { GeoOptimizationAgent } from "./specialized/GeoOptimizationAgent.js";
import { TopicalAuthorityAgent } from "./specialized/TopicalAuthorityAgent.js"; import { KeywordResearchAgent } from "./specialized/KeywordResearchAgent.js"; import { ContentBriefAgent } from "./specialized/ContentBriefAgent.js"; import { ContentWriterAgent } from "./specialized/ContentWriterAgent.js"; import { ContentOptimizationAgent } from "./specialized/ContentOptimizationAgent.js"; import { InternalLinkAgent } from "./specialized/InternalLinkAgent.js"; import { ContentRefreshAgent } from "./specialized/ContentRefreshAgent.js"; import { ContentImageAgent } from "./specialized/ContentImageAgent.js"; import { ContentCalendarAgent } from "./specialized/ContentCalendarAgent.js"; import { ContentLearningAgent } from "./specialized/ContentLearningAgent.js";
import { GBPOptimizationAgent } from "./specialized/GBPOptimizationAgent.js"; import { LocalRankAgent } from "./specialized/LocalRankAgent.js"; import { CitationAgent } from "./specialized/CitationAgent.js"; import { NAPCheckerAgent } from "./specialized/NAPCheckerAgent.js"; import { LocalCompetitorAgent } from "./specialized/LocalCompetitorAgent.js"; import { LocationPageAgent } from "./specialized/LocationPageAgent.js"; import { LocalSeoReportAgent } from "./specialized/LocalSeoReportAgent.js";
import { BacklinkDiscoveryAgent } from "./specialized/BacklinkDiscoveryAgent.js"; import { CompetitorBacklinkAgent } from "./specialized/CompetitorBacklinkAgent.js"; import { DigitalPRAgent } from "./specialized/DigitalPRAgent.js"; import { OutreachAgent } from "./specialized/OutreachAgent.js"; import { BacklinkMonitorAgent } from "./specialized/BacklinkMonitorAgent.js"; import { BrandMentionAgent } from "./specialized/BrandMentionAgent.js"; import { AuthorityReportAgent } from "./specialized/AuthorityReportAgent.js";

const AGENTS = [SeoAuditAgent, TechnicalSeoAgent, ContentStrategyAgent, BlogWriterAgent, WordPressAgent, GbpAgent, ReviewAgent, BacklinkAgent, InternalLinkingAgent, SchemaAgent, ReportAgent, NotificationAgent, SeoIntelligenceAgent, SeoStrategistAgent, AIQueryGeneratorAgent, AIVisibilityMonitorAgent, GeoOptimizationAgent, TopicalAuthorityAgent, KeywordResearchAgent, ContentBriefAgent, ContentWriterAgent, ContentOptimizationAgent, InternalLinkAgent, ContentRefreshAgent, ContentImageAgent, ContentCalendarAgent, ContentLearningAgent, GBPOptimizationAgent, LocalRankAgent, CitationAgent, NAPCheckerAgent, LocalCompetitorAgent, LocationPageAgent, LocalSeoReportAgent, BacklinkDiscoveryAgent, CompetitorBacklinkAgent, DigitalPRAgent, OutreachAgent, BacklinkMonitorAgent, BrandMentionAgent, AuthorityReportAgent];
export function createAgentRegistry(deps) { const registry = new AgentRegistry(); for (const Type of AGENTS) registry.register(new Type(deps)); return registry; }
